# Generated by Django 4.2.1 on 2026-08-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0011_normalize_engine_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='base_scale_nps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='dev_scale_nps',
            field=models.IntegerField(default=0),
        ),
    ]
